// <auto-generated />
using AwsBilling.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AwsBilling.Database.Migrations
{
    [DbContext(typeof(ReportsDbContext))]
    partial class ReportsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AwsBilling.Database.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ByteSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("byte_size");

                    b.Property<string>("CollectedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("collected_at_utc");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("page_count");

                    b.Property<string>("PeriodEnd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("period_end");

                    b.Property<string>("PeriodStart")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("period_start");

                    b.Property<string>("ServiceNames")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_names");

                    b.HasKey("Id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("AwsBilling.Database.ReportContent", b =>
                {
                    b.Property<long>("ReportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("report_id");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_json");

                    b.HasKey("ReportId");

                    b.ToTable("report_contents", (string)null);
                });

            modelBuilder.Entity("AwsBilling.Database.ReportContent", b =>
                {
                    b.HasOne("AwsBilling.Database.Report", "Report")
                        .WithOne("Content")
                        .HasForeignKey("AwsBilling.Database.ReportContent", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AwsBilling.Database.Report", b =>
                {
                    b.Navigation("Content");
                });
#pragma warning restore 612, 618
        }
    }
}
